freebsd_instance:
  image_family: freebsd-13-0

pkg_task:
  install_script: pkg install -y go

env:
  GOPROXY: https://proxy.golang.org

build_task:
  depends_on:
    - pkg
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  get_script: go get github.com/wneessen/go-pf
  build_script: go build github.com/wneessen/go-pf
  test_script: go test github.com/wneessen/go-pf
