freebsd_instance:
  image_family: freebsd-13-0

task:
  install_script: pkg install -y go

env:
  GOPROXY: https://proxy.golang.org

lint_task_task:
  name: GolangCI Lint
  container:
    image: golangci/golangci-lint:latest
  run_script: golangci-lint run -v --timeout 5m0s --out-format json > lint-report.json
  always:
    golangci_artifacts:
      path: lint-report.json
      type: text/json
      format: golangci

build_task:
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  get_script: go get github.com/wneessen/go-pf
  build_script: go build github.com/wneessen/go-pf
  test_script: go test github.com/wneessen/go-pf
